# MongoDB Atlas Database Connection Configuration
spring.data.mongodb.uri=mongodb+srv://aayamadmin:Pass9988@cluster0.pn061jt.mongodb.net/Aayam_hotel?retryWrites=true&w=majority&appName=Cluster0

# App Execution Port
server.port=8080

# Logging level for clean console debugging
logging.level.org.springframework.data.mongodb=DEBUG